### ISSUE TITLE
My collection

### ISSUE THREAD

**Issue by mrcbax** [neonprimetime/PhishingKitTracker#3]
You can find my collection here: https://github.com/LogoiLab/ActiveAntiPhish I have yara rules for detecting unique strings found in phishkits most of those strings are emails with the extension taken off. I don't know what help my data would be to you but there are almost 100 phishkit source zips, and yara rules compiled specifically to detect them.

**Comment by neonprimetime** [comment]
if your kits have #threatactoremail drop accounts in them I'd be glad to get the gpg password grep through them and upload the email/hashes to PhishingKitTracker.  It couldn't hurt :-) Perhaps help some good guy correlate a threat actor's activity & campaigns. Thanks

**Comment by neonprimetime** [comment]
you could dm me on twitter @neonprimetime

**Comment by mrcbax** [comment]
I don't have a Twitter but I can email.

**Comment by mrcbax** [comment]
Assuming this is good and can be closed. If you have any questions you know where you can contact me.
